// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3zUnu1RPdbmWiDl_EraE1HLrXXwsZHw',
    appId: '1:421886797820:web:7d112e67a323f2e9ed7479',
    messagingSenderId: '421886797820',
    projectId: 'final-exam-929b1',
    authDomain: 'final-exam-929b1.firebaseapp.com',
    storageBucket: 'final-exam-929b1.appspot.com',
    measurementId: 'G-Z2Q56JR55Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8d8JwjZnooUpiJQquzzPjSHkt_f79cZc',
    appId: '1:421886797820:android:7d5917524c41f5beed7479',
    messagingSenderId: '421886797820',
    projectId: 'final-exam-929b1',
    storageBucket: 'final-exam-929b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyFEG1MqTyghC1gwNSGp4xJHn7bMZExw',
    appId: '1:421886797820:ios:2d23f66fe33de39fed7479',
    messagingSenderId: '421886797820',
    projectId: 'final-exam-929b1',
    storageBucket: 'final-exam-929b1.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );
}
